name: Metadata Workflow
on: push
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            - name: Get repository metadata
              run: echo "${{ toJSON(github) }}"